version: '3.7'
services:
  golangapp:
    image: golang:1
    container_name: golangapp
    networks:
      - bridge-network
    expose:
      - "8001"

  flaskapp:
    image: good:v1   
    container_name: flaskapp
    networks:
      - bridge-network
    expose:
      - "8002"
    environment:
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=8002

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - golangapp
      - flaskapp
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge

